### ISSUE TITLE
Is there a way to update docker image with modifications to the code?

### ISSUE THREAD

**Issue by pancitmiki** [voiceip/oreka#115]
Hi,

I have modified the code and have been able to see the changes locally.
I need to compile these changes and put in a docker image so I can run it in CentOS.
How do I achieve this feat?
I'm also looking at `distribution\docker\Dockerfile.orkaudio` to understand what's happening inside.
I am running orkaudio in Ubuntu 20.04 locally.

Please advise.
Thank you

**Comment by kingster** [comment]
Hi @pancitmiki

The easiest option would be to modify this [line](https://github.com/voiceip/oreka/blob/85a8cb25723b844b730409ae692af138afedd139/distribution/docker/Dockerfile.orkaudio#L48)  to point to your fork so that it builds with your changes.
