### ISSUE TITLE
audio file name extension is mcf

### ISSUE THREAD

**Issue by harold-yh** [voiceip/oreka#116]
RUNNING OS：centos7.9
BUILD OS：ubuntu 14.04.6

I set the audio format with pcmwav，but i got file ext is :mcf。
etc:20220827_202929_EHDU.mcf
<StorageAudioFormat>pcmwav</StorageAudioFormat>

**Comment by kingster** [comment]
Mcf is the native file. This looks like config error or processing error. 

Could you share the config file that you are using? Also please share the commands of how you are launching orkaudio process.

**Comment by harold-yh** [comment]
I has tried the command ./orkaudio debug and ./orkaudio，i got the same mcf file.

the config:

<config>
        <AudioOutputPath>/home/wav</AudioOutputPath>

        <CapturePlugin>libvoip.so</CapturePlugin>

        <CapturePluginPath>./lib</CapturePluginPath>

        <StorageAudioFormat>pcmwav</StorageAudioFormat>
        <StereoRecording>true</StereoRecording>
        <TapeNumChannels>2</TapeNumChannels>
        <AudioFileBitRate>8000</AudioFileBitRate>

        <DeleteNativeFile>yes</DeleteNativeFile>

        <DeleteFailedCaptureFile>yes</DeleteFailedCaptureFile>

        <EnableReporting>no</EnableReporting>
        <TrackerHostname>localhost</TrackerHostname>
        <TrackerTcpPort>8081</TrackerTcpPort>

        <NumBatchThreads>16</NumBatchThreads>

        <AudioFileOwner>tomcat</AudioFileOwner>
        <AudioFileGroup>tomcat</AudioFileGroup>
        <AudioFilePermissions>644</AudioFilePermissions>

        <VoIpPlugin>
                <PcapSocketBufferSize>67108864</PcapSocketBufferSize>
                <IpFragmentsReassemble>true</IpFragmentsReassemble>
                <Devices>em4</Devices>
                <PcapFilter>host 11.5.213.202</PcapFilter>
        </VoIpPlugin>
</config>

**Comment by harold-yh** [comment]
Sorry，I check the config，I lost the:<TapeProcessors>BatchProcessing, Reporting</TapeProcessors>。
when I added , it works。
Thanks.
