### ISSUE TITLE
Eclipse and java

### ISSUE THREAD

**Issue by steven1978oz** [voiceip/oreka#18]
Thank you for making this great project available.
I am just trying the compile  orkweb orktrack orkbasej following the BUILD_JAVA.txt for the updates you made in December 2019. Using Eclipse 2019 and Java 8. Is there a repository available for the web components or a cheat sheet for us that's just learning how to compile? Many Thanks Steven

**Comment by kingster** [comment]
BUILD_JAVA.txt is now obsolete since it belonged to the original unmaintained project. I have switched the earlier format to maven based projects. 

If you want to now compile in eclipse, just import the project as a maven project, and it should just compile as it would configure eclipse automatically. 

Let me know if you still face any issues.

**Comment by steven1978oz** [comment]
Thank you. worked great fro the orkweb but seem to be missing classes for orktrack.

**Comment by kingster** [comment]
Shouldn't be like that, what is the error that you are getting?

**Comment by steven1978oz** [comment]
I think eclipse 2019 is the issue. I cannot not see classes in the orkweb target WEB-INF tree.
Can the classes be used from orkbasej? Eclipse wont export only jar type. I added this to the pom.xml file orkbasej now I can see the classes.   
<packaging>war</packaging>
Sorry very green at this

**Comment by wrivera2022** [comment]
Hello,

I'm having an issue compiling using Eclipse 2019. I tried to import the project to Maven and I'm running java 8.

Thanks for any help you can provide and thanks for updating the Oreka apps!
The error are on the screenshot below:
![image](https://user-images.githubusercontent.com/61894159/76134480-10b2c900-5ff5-11ea-83e6-59373b7b28f0.png)

![image](https://user-images.githubusercontent.com/61894159/76134497-258f5c80-5ff5-11ea-8eae-a650a790ea67.png)

**Comment by kingster** [comment]
As part of https://github.com/voiceip/oreka/pull/17 few of the pojos were migrated to use lomok for auto generation boilerplate code. Try looking for eclipse plugin of lomok, that should fix your compilation issue.

**Comment by steven1978oz** [comment]
I have just added lombok as per wrivera2022 issue and ninety percent of the errors are gone. only have these errors now. ![image](https://user-images.githubusercontent.com/61574153/76136958-1d7dfe00-6083-11ea-9f96-8f3ea716510c.png)

**Comment by wrivera2022** [comment]
Thanks for your help @kingster. That fixed a lot of errors but I'm having the same error as @steven1978oz

**Comment by steven1978oz** [comment]
I ended up using mvn on Ubuntu 16.04 to compile. I had no luck with Eclipse. I had a few other errors which was resolved by having the missing plugins. Onto another issue with OrkAudio not sending updates to orktrack. tcpdump is show no requests for connections but the wav files are created in the audio folder. Its like Orkaudio does not have permission to access the NIC.

**Comment by kingster** [comment]
@steven1978oz  I guess eclipse has some compatibility issues with AspectJ.
Regarding the issue " OrkAudio not sending updates to orktrack." This shouldn't happen,  It works as expected for me. How are you building orkaudio? Can you try out the binary releases or follow the building step of orkaudio?

**Comment by steven1978oz** [comment]
I used the Bintray package just the other night. Seems to capture and log ok in the var/log/orkaudio/audio folders but does not send the data to orktrack. I have a version 1.7 collector that can send to orktrack from a different machine so I know orktrack seems to be working ok.

**Comment by kingster** [comment]
Can you please install the above version, and also share your config file, please?  We are using in our production and we don't see any issue. Also, how are you running the service?

**Comment by steven1978oz** [comment]
Happy days :) you are a legend!  The above orkaudio package worked a treat. Its now connecting to orktrack and ortrack is writing to the database. I am just running "orkaudio debug" currently for testing and live debuging.

**Comment by steven1978oz** [comment]
Sorry one more question. I have noticed that the current orktrack does not seem to build the database if one is dropped. I made a lot of test calls today so I dropped the database to clean it up. On version 1.7 it seems to recreate it.

**Comment by kingster** [comment]
The database needs to exist. The tables are created automatically on application start. If you have dropped the tables, then just restart the tomcat server and the application would auto-create the tables on startup.

**Comment by steven1978oz** [comment]
I have recreated the database "create database oreka" but still no go. I have noticed no files from the orkbasej target folder are in the ortrack folder. Are these required? Looking at the orktrack folder HibernateManager is missing and did not copy across from the orkbasej build so I guess I still have minor issues with the compiling

**Comment by kingster** [comment]
@steven1978oz you might have an issue with compilation. I would suggest you to use mvn for compilation and then deploy the war into tomcat folder. Alternatively, use the prebuild binary packages to install.
