### ISSUE TITLE
Couldn't find out the source codes related to libh323voip.so

### ISSUE THREAD

**Issue by AlbertZheng** [voiceip/oreka#21]
I noticed there is "Use libh323voip.so for Avaya, Nortel Unistim, H.323 and MGCP" in config.xml, but couldn't find out the source codes related to `libh323voip.so` under `audiocaptureplugins` directory. Could you please share the source codes? Thanks.

**Comment by kingster** [comment]
libh323voip.so would be a paid plugin from orekx which is licensed version and not available as part of opensource.

The default capture plugin would still capture all voip media. What specific kind of scenario capture (avaya/h232/others) are you looking for?

**Comment by AlbertZheng** [comment]
@kingster I am looking for avaya with h.323 stack.

**Comment by kingster** [comment]
`libvoip.so` would also capture `h.323` media, just that extended metadata wouldn't be captured (it would capture the both side IP address). You will be able to play all recordings. AFAIK some avaya deployments has some segment on SIP so maybe check if your use-case has such option which would allow to capture metadata and rtp.

Last I checked `libh323voip.so` is available from orekx on purchase via their `oreka tr` product.
