### ISSUE TITLE
Orkweb - Download and Player Issues

### ISSUE THREAD

**Issue by NelsonBA81** [voiceip/oreka#41]
Hello,

I've been doing some additional testing, and I've noticed that the player seems it is not working.
I just hit play, I see in browser developer mode (Chrome), a download of media file. with 200 response, but still, no sound, just play-stop condition in player.

Also, you've mentioned that the orkweb has the possibility to download the recordings, but, I don't see or where I can do that.

When possible, please let me know how to solve these issues.

Thank you and
Best regards,
Nelson

**Comment by kingster** [comment]
This looks like an orkaudio problem where your file is not transcoded properly into a format that Chrome can play. Try changing the output format to a chrome supported format, and then try again.

**Comment by NelsonBA81** [comment]
Hello,

Since I'm a bit lost on this, can you please suggest a format which may work with Chrome and at the same time is also supported by orkaudio?

Thank  you and
Best regards,
Nelson

**Comment by NelsonBA81** [comment]
> Hi Nelson,
> 
> If you haven't solved this issue, take a look at /etc/orkaudio/config.xml
> and change the StorageAudioFormat from gsm to pcmwav
> 
> `<!-- Audio file storage format: choose from: native, gsm, ulaw, alaw, pcmwav --> <StorageAudioFormat>gsm</StorageAudioFormat>`

Thanks! But unfortunately, it generates wav files with heavier footprint on disk, do you know if there is other format which could work in chrome but with a reduced footprint?

**Comment by kingster** [comment]
Well, you can try the 'opus' format. Its small in footprint and chrome documentation says that it supports the format.

Let us know if it works for you :)

**Comment by michaelc06** [comment]
I can confirm 'opus' format works on Chrome, Firefox and Edge. I would prefer mp3 (for portability) but it's not currently supported in orkaudio.

**Comment by NelsonBA81** [comment]
thanks @kingster and @michaelc06, that format works fine and the footprint is small.
now the only possible defect that I've noticed is the playback slider, as I drag the slider forward, the playback continues, does not skip... does this behavior happen to you too?
I believe that is not related to the format, since with pcmwave, the behavior was the same...

**Comment by michaelc06** [comment]
The playback slider works fine on Firefox but not on Chrome and Edge. However, if you download the audio files and then drag it into the Chrome or Edger browser then the playback slider function correctly.
