### ISSUE TITLE
orkaudio on Ubuntu 20.04

### ISSUE THREAD

**Issue by mikoday** [voiceip/oreka#46]
Hello, I tried to install orkaudio on Ubuntu 20.04, this is unsupported system still, but maybe you can give me some hints how to do this?

```
root[127824]: Starting Oreka Audio Recorder
orkaudio[127832]: /usr/sbin/orkaudio: symbol lookup error: /usr/local/lib/liborkbase.so.0: undefined symbol: _ZTIN11xercesc_3_113XMLEntityD>
systemd[1]: orkaudio.service: Control process exited, code=exited, status=127/n/a
```

**Comment by kingster** [comment]
I haven't personally tried ubuntu 20.x but as reported earlier, It seems that liblog4cxx10-dev and libxerces-c3.1 on which the current build are made are missing/have changed their package name. You can try manually installing them and see if that fixes this issue. Alternatively, you could try the docker image also, which would always work independently of the os version.

**Comment by mikoday** [comment]
I decided to rebuld orkaudio.deb and rename package names in this way accordingly:

```diff
- Depends: curl, unzip, libboost-dev, libpcap-dev, libsndfile1-dev, libapr1-dev, libspeex-dev, liblog4cxx10-dev, libace-dev, libopus-dev, libxerces-c3.1, daemontools
+ Depends: curl, unzip, libboost-dev, libpcap-dev, libsndfile1-dev, libapr1-dev, libspeex-dev, liblog4cxx10v5, libace-dev, libopus-dev, libxerces-c3.2, daemontools
```
Then I was able to install it, however I get symbol lookup error like in the first post.

As a last resort, I will use a docker, but do you have any plans for native support for newer packages?

**Comment by kingster** [comment]
Just changing the depends's might not work, as the binary against which this was built doesn't match with the new version, hence the symbol error.

Yes, I do have plans soon to create a build for ubuntu 20.x as soon as I get some time.

**Comment by kingster** [comment]
@mikoday Could you give this build for Ubuntu 20.x a try and confirm if this works for you ?
 
[orkaudio_focal.deb.zip](https://github.com/voiceip/oreka/files/6223019/orkaudio_focal.deb.zip)

**Comment by mikoday** [comment]
@kingster it works! orkaudio.service is active (running)
I will check further settings. Thanks.
