### ISSUE TITLE
Default orkweb login?

### ISSUE THREAD

**Issue by rpelletierrefocus** [voiceip/oreka#49]
Tried admin/admin. Can't find any documentation anywhere.

**Comment by kingster** [comment]
Yup, that correct. Update the same in the installation documentation. 

Usually, that happens when your database config is not correct. I would suggest that you check your tomcat logs for the error/ update the config with the correct MySQL credentials.

**Comment by rpelletierrefocus** [comment]
Thank you that was indeed the issue.

Sent from my iPhone

On Apr 1, 2021, at 10:41 AM, Kinshuk Bairagi ***@***.***> wrote:

﻿

Yup, that correct. Update the same in the installation documentation.

Usually, that happens when your database config is not correct. I would suggest that you check your tomcat logs for the error/ update the config with the correct MySQL credentials.
