### ISSUE TITLE
caputuring from pipe (stdin / stdout)

### ISSUE THREAD

**Issue by duffy6** [voiceip/oreka#5]
I have a script running (fritzdump.sh) which captures the traffic directly from my router into a pipe:

in this example it is piped to tshark:

`wget --no-check-certificate -qO- $FRITZIP/cgi-bin/capture_notimeout?ifaceorminor=$IFACE\&snaplen=\&capture=Start\&sid=$SID | /usr/bin/tshark -r -`

I would like to "forward" this traffic to Oreka?

Is this possible?

Capturing the traffic to a pcap file first and then analyzing with wireshark is way to complicated. I am looking for an automated solution. I don't want to:

save pcap -> send manually pcap to oreka

greetz duffy6

**Comment by kingster** [comment]
I don't think this is possible as of now, as the current pcap readers doesn't support this. 

I don't have access to a fritzdump.sh device to try out this scenario yet.

**Comment by kingster** [comment]
A possible way is to create a virtual interface and inject the pcap file into it, then configure orkaudio to capture from this virtual interface.

References
1. https://serverfault.com/questions/912331/how-to-send-tcpdump-captured-traffic-directly-to-an-interface
2. https://stackoverflow.com/questions/1953300/how-to-send-pcap-file-packets-on-nic/2463471#2463471
 
Please do try this out if you are still trying to search for a solution. Please do report/reopen if this worked/didn't work for your use-case.
