### ISSUE TITLE
support run inside docker

### ISSUE THREAD

**Issue by syklevin** [voiceip/oreka#7]
It would be great if could provide prebuilt docker image

**Comment by kingster** [comment]
Oreka primary works with mirrored traffic coming from a span port. I am not sure how to attach an ethernet port entirely to docker instance. Probably you can help in this?

**Comment by kingster** [comment]
Hi @syklevin 

We have pushed some beta docker images, do try them out and let us know if this works for you. This image now captures traffic from `eth0` interface

```
docker run --net=host -v /var/log/orkaudio:/var/log/orkaudio -it voiceip/orkaudio
```

This would run on linux hosts (as the `--net=host` command for docker is supported in linux hosts only). For mac/windows probably you will have to run a docker based pjsua to test the capture like here  #10.

**Comment by kingster** [comment]
Docker is now supported. Please follow the readme to refer how to use docker images
