### ISSUE TITLE
orktrack build error, mvn clean package ?

### ISSUE THREAD

**Issue by honyyang** [voiceip/oreka#78]
> mvn clean package
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< net.sf.oreka:orktrack >------------------------
[INFO] Building orktrack 0.0.2-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ orktrack ---
[INFO] Deleting /root/oreka/orktrack/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ orktrack ---
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ orktrack ---
[WARNING] File encoding has not been set, using platform encoding ANSI_X3.4-1968, i.e. build is platform dependent!
[INFO] Compiling 24 source files to /root/oreka/orktrack/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.768 s
[INFO] Finished at: 2021-12-22T04:11:41Z
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/usr/share/maven/conf/logging/
constituent[1]: file:/usr/share/maven/lib/sisu-inject.jar
constituent[2]: file:/usr/share/maven/lib/jcl-over-slf4j.jar
constituent[3]: file:/usr/share/maven/lib/slf4j-api.jar
constituent[4]: file:/usr/share/maven/lib/wagon-provider-api.jar
constituent[5]: file:/usr/share/maven/lib/cdi-api.jar
constituent[6]: file:/usr/share/maven/lib/maven-resolver-transport-wagon.jar
constituent[7]: file:/usr/share/maven/lib/wagon-http-shaded.jar
constituent[8]: file:/usr/share/maven/lib/plexus-cipher.jar
constituent[9]: file:/usr/share/maven/lib/maven-resolver-impl.jar
constituent[10]: file:/usr/share/maven/lib/plexus-sec-dispatcher.jar
constituent[11]: file:/usr/share/maven/lib/maven-resolver-connector-basic.jar
constituent[12]: file:/usr/share/maven/lib/maven-model-3.x.jar
constituent[13]: file:/usr/share/maven/lib/maven-compat-3.x.jar
constituent[14]: file:/usr/share/maven/lib/maven-embedder-3.x.jar
constituent[15]: file:/usr/share/maven/lib/javax.inject.jar
constituent[16]: file:/usr/share/maven/lib/sisu-plexus.jar
constituent[17]: file:/usr/share/maven/lib/commons-io.jar
constituent[18]: file:/usr/share/maven/lib/maven-artifact-3.x.jar
constituent[19]: file:/usr/share/maven/lib/maven-shared-utils.jar
constituent[20]: file:/usr/share/maven/lib/plexus-utils.jar
constituent[21]: file:/usr/share/maven/lib/maven-repository-metadata-3.x.jar
constituent[22]: file:/usr/share/maven/lib/wagon-file.jar
constituent[23]: file:/usr/share/maven/lib/guava.jar
constituent[24]: file:/usr/share/maven/lib/maven-builder-support-3.x.jar
constituent[25]: file:/usr/share/maven/lib/maven-resolver-spi.jar
constituent[26]: file:/usr/share/maven/lib/plexus-interpolation.jar
constituent[27]: file:/usr/share/maven/lib/maven-resolver-api.jar
constituent[28]: file:/usr/share/maven/lib/jsr250-api.jar
constituent[29]: file:/usr/share/maven/lib/guice.jar
constituent[30]: file:/usr/share/maven/lib/commons-cli.jar
constituent[31]: file:/usr/share/maven/lib/maven-plugin-api-3.x.jar
constituent[32]: file:/usr/share/maven/lib/maven-core-3.x.jar
constituent[33]: file:/usr/share/maven/lib/maven-settings-builder-3.x.jar
constituent[34]: file:/usr/share/maven/lib/commons-lang3.jar
constituent[35]: file:/usr/share/maven/lib/plexus-component-annotations.jar
constituent[36]: file:/usr/share/maven/lib/maven-resolver-util.jar
constituent[37]: file:/usr/share/maven/lib/maven-settings-3.x.jar
constituent[38]: file:/usr/share/maven/lib/maven-slf4j-provider-3.x.jar
constituent[39]: file:/usr/share/maven/lib/jansi.jar
constituent[40]: file:/usr/share/maven/lib/maven-resolver-provider-3.x.jar
constituent[41]: file:/usr/share/maven/lib/maven-model-builder-3.x.jar
constituent[42]: file:/usr/share/maven/lib/aopalliance.jar
---------------------------------------------------
Exception in thread "main" java.lang.AssertionError
        at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
        at jdk.compiler/com.sun.tools.javac.util.Assert.check(Assert.java:46)
        at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:247)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.readSourceFile(JavaCompiler.java:837)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ImplicitCompleter.complete(JavacProcessingEnvironment.java:1535)
        at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:642)
        at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1326)
        at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.complete(Type.java:1140)
        at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.getTypeArguments(Type.java:1066)
        at jdk.compiler/com.sun.tools.javac.code.Printer.visitClassType(Printer.java:237)
        at jdk.compiler/com.sun.tools.javac.code.Printer.visitClassType(Printer.java:52)
        at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.accept(Type.java:993)
        at jdk.compiler/com.sun.tools.javac.code.Printer.visit(Printer.java:136)
        at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument(AbstractDiagnosticFormatter.java:199)
        at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments(AbstractDiagnosticFormatter.java:167)
        at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:111)
        at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
        at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument(AbstractDiagnosticFormatter.java:185)
        at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments(AbstractDiagnosticFormatter.java:167)
        at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:111)
        at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
        at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic.getMessage(JCDiagnostic.java:788)
        at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$DiagnosticSourceUnwrapper.getMessage(ClientCodeWrapper.java:799)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:149)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:785)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by kingster** [comment]
Can you share what version & variant of Java and maven you are trying to build the package? Our CI builds haven't reported this issue.

**Comment by honyyang** [comment]
> Can you share what version & variant of Java and maven you are trying to build the package? Our CI builds haven't reported this issue.

ubuntu 18.04
maven 3.6
openjdk-11

Could you share your verion of openjdk and maven in you CI system ?
Or Provide installation documention about orktrack ?

**Comment by kingster** [comment]
Can you please try with JDK8 instead ?

PS: Our CI Pipelines uses [adopt java8](https://github.com/voiceip/oreka/blob/master/.github/workflows/main.yml#L74-L82)

Installation documentation is available on our [wiki](https://github.com/voiceip/oreka/wiki/Installation)

**Comment by honyyang** [comment]
> Can you please try with JDK8 instead ?
> 
> PS: Our CI Pipelines uses [adopt java8](https://github.com/voiceip/oreka/blob/master/.github/workflows/main.yml#L74-L82)
> 
> Installation documentation is available on our [wiki](https://github.com/voiceip/oreka/wiki/Installation)

ubuntu 18.04
maven 3.6
openjdk-8

But, mvn clean package and compile error.


[INFO] 55 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.288 s
[INFO] Finished at: 2021-12-23T10:02:28Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project orktrack: Compilation failure: Compilation failure: 
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/UserManager.java:[22,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/Port.java:[30,24] package org.apache.log4j does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/Port.java:[31,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/UserManager.java:[43,61] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.UserManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/messages/TapeMessage.java:[33,24] package org.apache.log4j does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/messages/TapeMessage.java:[34,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/messages/TapeMessage.java:[35,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/messages/MetadataMessage.java:[31,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/messages/MetadataMessage.java:[32,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/Port.java:[44,16] cannot find symbol
[ERROR]   symbol:   class Logger
[ERROR]   location: class net.sf.oreka.orktrack.Port
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/Port.java:[86,65] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.Port
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/Port.java:[93,76] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.Port
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/Port.java:[114,73] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.Port
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/Port.java:[135,76] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.Port
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/Port.java:[188,64] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.Port
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/messages/TapeMessage.java:[44,16] cannot find symbol
[ERROR]   symbol:   class Logger
[ERROR]   location: class net.sf.oreka.orktrack.messages.TapeMessage
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/ProgramManager.java:[25,24] package org.apache.log4j does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/ProgramManager.java:[26,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/ProgramManager.java:[27,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/ProgramManager.java:[31,16] cannot find symbol
[ERROR]   symbol:   class Logger
[ERROR]   location: class net.sf.oreka.orktrack.ProgramManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/ProgramManager.java:[81,72] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.ProgramManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/ProgramManager.java:[100,85] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.ProgramManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/ServiceManager.java:[20,24] package org.apache.log4j does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/ServiceManager.java:[21,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/ServiceManager.java:[25,16] cannot find symbol
[ERROR]   symbol:   class Logger
[ERROR]   location: class net.sf.oreka.orktrack.ServiceManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/ServiceManager.java:[27,81] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.ServiceManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/ServiceManager.java:[45,62] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.ServiceManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/messages/UserStateMessage.java:[26,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/messages/UserStateMessage.java:[27,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/test/ProgramTest.java:[20,23] package junit.framework does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/test/ProgramTest.java:[21,23] package junit.framework does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/test/ProgramTest.java:[22,23] package junit.framework does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/test/ProgramTest.java:[33,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/test/ProgramTest.java:[34,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/test/ProgramTest.java:[36,34] cannot find symbol
[ERROR]   symbol: class TestCase
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/test/ProgramTest.java:[44,23] cannot find symbol
[ERROR]   symbol:   class Test
[ERROR]   location: class net.sf.oreka.orktrack.test.ProgramTest
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/PortManager.java:[24,24] package org.apache.log4j does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/PortManager.java:[25,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/PortManager.java:[26,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/PortManager.java:[34,16] cannot find symbol
[ERROR]   symbol:   class Logger
[ERROR]   location: class net.sf.oreka.orktrack.PortManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/PortManager.java:[52,51] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.PortManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/PortManager.java:[62,58] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.PortManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/PortManager.java:[95,57] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.PortManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/PortManager.java:[157,54] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.PortManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/TapeManager.java:[10,27] package org.hibernate.query does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/TapeManager.java:[18,17] cannot find symbol
[ERROR]   symbol:   class Logger
[ERROR]   location: class net.sf.oreka.orktrack.TapeManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/TapeManager.java:[32,56] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.TapeManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/TapeManager.java:[39,61] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.TapeManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/TapeManager.java:[59,67] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class net.sf.oreka.orktrack.TapeManager
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/test/PortTest.java:[20,23] package junit.framework does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/test/PortTest.java:[21,23] package junit.framework does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/test/PortTest.java:[22,23] package junit.framework does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/test/PortTest.java:[38,21] package org.hibernate does not exist
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/test/PortTest.java:[40,31] cannot find symbol
[ERROR]   symbol: class TestCase
[ERROR] /root/oreka/orktrack/src/main/java/net/sf/oreka/orktrack/test/PortTest.java:[48,23] cannot find symbol
[ERROR]   symbol:   class Test
[ERROR]   location: class net.sf.oreka.orktrack.test.PortTest
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by kingster** [comment]
Hi

Well I was unable to replicate this issue, even on a fresh VM, and it has built it properly. Can you please try it on a fresh VM or share the exact steps to replicate the issue.

```
vagrant init bento/ubuntu-18.04
sudo apt-get install openjdk-8-jdk maven
```

OS : Ubuntu 18.04.6 LTS
MVN : 3.6.0
OpenJDK: 1.8.0_312

```
root@vagrant:/home/vagrant# java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~18.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
root@vagrant:/home/vagrant# mvn -version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_312, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-163-generic", arch: "amd64", family: "UNIX"
root@vagrant:/vagrant# mvn clean install  -DskipTests -Dmaven.test.skip=true
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] orkbasej                                                           [jar]
[INFO] orktrack                                                           [war]
[INFO] orkweb                                                             [war]
[INFO] orekaj-parent                                                      [pom]
[INFO]
[INFO] -----------------------< net.sf.oreka:orkbasej >------------------------
[INFO] Building orkbasej 0.0.2-SNAPSHOT                                   [1/4]
[INFO] --------------------------------[ jar ]---------------------------------
....
....
....
....
[INFO] Reactor Summary for orekaj-parent 0.0.2-SNAPSHOT:
[INFO]
[INFO] orkbasej ........................................... SUCCESS [01:34 min]
[INFO] orktrack ........................................... SUCCESS [01:02 min]
[INFO] orkweb ............................................. SUCCESS [ 13.863 s]
[INFO] orekaj-parent ...................................... SUCCESS [  0.007 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:51 min
[INFO] Finished at: 2021-12-23T10:18:38Z
[INFO] ------------------------------------------------------------------------

```

**Comment by honyyang** [comment]
> 

Yes, success

 I built in subdirectory `oreka/orktrack`, actually should build in root directory `oreka`.

**Comment by kingster** [comment]
There are multiple modules, hence you would either need to build them in sequence or build in the top directory for maven to automatically build them in sequence.  

Please reopen this issue if you still face any issues.
