### ISSUE TITLE
issue in build commands for orkaudio

### ISSUE THREAD

**Issue by Tejas-11** [voiceip/oreka#8]
While running the build commands for orkaudio specified in BUILD_C++ I received the following error "G729Codec.h:17:12: fatal error: bcg729/encoder.h: No such file or directory
". I request that u update the BUILD_C++ file to include the commands to build the g729 library before the commands to build orkaudio.

**Comment by kingster** [comment]
Please refer to the [README](https://github.com/voiceip/oreka/blob/master/README.md#building) for current build instructions. [The BUILD_C++ refers to the original build instructions at http://oreka.sourceforge.net/ ]

**Comment by Tejas-11** [comment]
Thank you
