### ISSUE TITLE
Live Streaming not working

### ISSUE THREAD

**Issue by salesAbhin** [voiceip/oreka#85]
I am trying to get the live stream as per the doc but no process starts at 59160.

**Comment by kingster** [comment]
Hi @salesAbhin

The official Live Stream doc that you have seen on oreka website is a paid feature, hence it is not available out of the box. However there is a beta open source version of livestream at #45 which you can try out. The documentation for this is available at https://github.com/voiceip/oreka/wiki/Live-Streaming

**Comment by salesAbhin** [comment]
h

> Hi @salesAbhin
> 
> The official [Live Stream](https://www.orecx.com/live-monitoring/) feature that you have seen on oreka website is a paid feature, hence it is not available out of the box. However there is a beta open source version of livestream at #45 which you can try out. The documentation for this is available at https://github.com/voiceip/oreka/wiki/Live-Streaming

Hey thanks for the reply , I tried out the oreka server with the same configuration however there was no process running at port 59160

**Comment by kingster** [comment]
Did you build from that branch? That code isn't merged yet, hence just changing config wouldn't work with the released version . You need to compile the code from that branch / use a precompiled version from the CI.

**Comment by kingster** [comment]
Here are the binaries from that pr which you can install and then follow the instructions in the wiki

https://github.com/voiceip/oreka/actions/runs/1653936023

**Comment by salesAbhin** [comment]
> Here are the binaries from that pr which you can install and then follow the instructions in the wiki
> 
> https://github.com/voiceip/oreka/actions/runs/1653936023

Hey thanks for the build was struggling to resolve the errors , let me check

**Comment by salesAbhin** [comment]
> > Here are the binaries from that pr which you can install and then follow the instructions in the wiki
> > https://github.com/voiceip/oreka/actions/runs/1653936023
> 
> Hey thanks for the build was struggling to resolve the errors, let me check

Thanks for the build I tried and got the live stream, However when I played the stream via vlc media player using RTMP link it sounded very choppy and stuttered. Is this a known issue with the existing implementation or I am missing some configuration.

**Comment by kingster** [comment]
The current version supports only basic g711 calls only. Was the call that you tried by any chance was of different codec?

**Comment by salesAbhin** [comment]
> The current version supports only basic g711 calls only. Was the call that you tried by any chance was of different codec?

No, it was g711 but the vlc sound was really choppy I tried to increase the tempo of the playback but no luck. Is there some configuration at Nginx like sample rate or something that needs to be tweaked?

**Comment by kingster** [comment]
Well it could be that VLC doesn't support G711 codec and hence the audio isn't clear, can you please try it with [ffplay](https://ffmpeg.org/ffplay.html). We use this application to verify our steams and it has been always crystal clear with this.

**Comment by salesAbhin** [comment]
> Well it could be that VLC doesn't support G711 codec and hence the audio isn't clear, can you please try it with [ffplay](https://ffmpeg.org/ffplay.html). We use this application to verify our steams and it has been always crystal clear with this.

Okay, I am getting the stream clear now, wondering if I can not mix streams and get separate channels. Is there a way to do it in the current project?

**Comment by kingster** [comment]
Great!! Yes should be able to split the streams (as the streams are stereo in nature) and play them separately using either ffplay [filters](https://ffmpeg.org/ffplay.html#While-playing) or using ffmpeg to [split](https://ffmpeg.org/ffplay-all.html#channelsplit) the streams or having any custom player which can play g711 media.
