### ISSUE TITLE
how use siprec plugin?

### ISSUE THREAD

**Issue by honyyang** [voiceip/oreka#86]
I use opensips as siprec's client (SRC) , 

```
SRC (Session Recording Client) - this is the SIP component in the call's path which triggers the call recording - this is where OpenSIPS gets involved.
SRS (Session Recording Server) - this is the actual recorder, the SIP component that only receives the traffic forked by the SRC and dumps it in a file - an example of a SRS is Oreka, an Open Source Enterprise Telephony Recording provided by OrecX.

note: [https://www.opensips.org/Documentation/Tutorials-SIPREC-3-2](url)
```

but how I use siprec as server (SRS) on oreka ? could you give me some advice ,very thanks !

**Comment by kingster** [comment]
From the documentation that you have shared it reffers to a commercial edition of oreka recorder and not the opensource version. 

As per my understanding oreka(opensource version) works in passive mode of siprec, and in this mode, orkaudio would keep capturing sip+rtp as long as they arrive on the capture interface.
