### ISSUE TITLE
Download button for recorded sounds

### ISSUE THREAD

**Issue by amousavii** [voiceip/oreka#9]
Is it possible to implement a download button for recorded sounds ?

**Comment by kingster** [comment]
Shouldbe, you would need to make change in the orkweb package. I haven't yet touched that package as I use [voiceip/oreka-api](https://github.com/voiceip/oreka-api) to access the recordings programatically via api.

**Comment by kingster** [comment]
Hi @amousavii I have attempted to update orkweb to offer both download and play feature in #16 . do try it out and let me know if this is what you were looking for.
