### ISSUE TITLE
Stream to audio port

### ISSUE THREAD

**Issue by etlweather** [voiceip/oreka#94]
Hello,

I am looking to see if it is possible to send the captured audio to the computer's audio jack instead of to a wav file. There would always be only one call going through orkaudio.

It does not seem to be an option out-of-the box and I am interesting in programming this but I have very little experience with C++ so any pointer would be welcome.

**Comment by kingster** [comment]
Hi 

Well, I can think of 2 ways to get this done.

1) Use existing options available, but this may mean chaining up a few things 

    Enable [LiveStream](https://github.com/voiceip/oreka/wiki/Live-Streaming) option, and use ffplay to  playout the stream. This option will work as long as the call is running. If the call is disconnected/redialed then you have to retrigger the ffplay with the new ID.

2) Modify the [LiveStream.cpp](https://github.com/voiceip/oreka/blob/onDemand/orkaudio/filters/LiveStream/LiveStreamFilter.cpp) to directly play the media to speakers. With this option, you will need no other steps.

**Comment by etlweather** [comment]
LiveStream - that's part of the `onDemand` branch?

**Comment by etlweather** [comment]
oh, never mind, my answer is in your second link.
