### ISSUE TITLE
QUESTION about Orecx

### ISSUE THREAD

**Issue by jmrbcu** [voiceip/oreka#95]
Hello, I was looking at the Orecx web page, in the open-source section: https://www.orecx.com/open-source/ and the project the referenced on GitHub is this one: https://github.com/voiceip/oreka and not the one they own: https://github.com/OrecX/Oreka
So, my question is, which one is the upstream right now. Yours has support for some stuff they don't have but as I can see this repo is not in sync with the original one (from Orecx). Is that a type in their webpage?

**Comment by kingster** [comment]
Hi @jmrbcu 

This repo has been built over the OrecX/Oreka, and has major features + security fixes over the original repo and offers binary releases. 

I often at times do merge in any fix that happens upstream but their last few commits broke the build pipeline, hence I am yet to make a fix for that.

**Comment by jmrbcu** [comment]
Yes, but what about them (Orecx) referencing this project (https://github.com/voiceip/oreka) as the open-source one and not their own, also open-source (https://github.com/OrecX/Oreka)?
Please, look at: https://www.orecx.com/open-source/, where the link to GitHub is. 

Here is the snippet from their website:

**VoIP ready free voice call recording softwareOreka**

Oreka GPL is a free, VoIP-ready, open source call recording software, which can capture and retrieve calls via a browser-based interface. [Downloaded](https://github.com/voiceip/oreka) for free, the Oreka GPL open-source voice call recording software is the only free open source recording software on the planet that can be downloaded in just 30 minutes and requires no maintenance.

**Comment by kingster** [comment]
Well, I can be only super happy about this :) It's more probably because this repo has more features than their one!

**Comment by jmrbcu** [comment]
Just go and check it out, I think it is a typo but not sure. That said, it is nice to be mentioned there. I also have my own repo based on both, this one and theirs with the best of both (only for OrkAudio, I don't use OrkTrack/OrkWeb) + some other private stuff and bug fixes I will be open-sourcing soon. As I said before in another issue, I am planning to move away from Autotools and add CMake support to be fully independent of the build system they use.

**Comment by kingster** [comment]
Sure will do.

Btw, I have just merged changes from their repo #25, so this repo should be up to date with the upstream.  

> I also have my own repo based on both, this one and theirs with the best of both (only for OrkAudio, I don't use OrkTrack/OrkWeb) + some other private stuff and bug fixes I will be open-sourcing soon.

You would be willing to create a PR so that everyone can benefit from your fixes? 

Regarding CMake, I think that would be a really good improvement, both in terms of maintainability and build time.

**Comment by jmrbcu** [comment]
> Btw, I have just merged changes from their repo #25, so this repo should be up to date with the upstream.

Nice, I still have to pull those changes to mine. I will probably do it today after I finish with some features I am adding. 

> You would be willing to create a PR so that everyone can benefit from your fixes?
Some of the features are closed-source, but some are not; I am negotiating to release them!

> Regarding CMake, I think that would be a really good improvement, both in terms of maintainability and build time.
That is a work in progress, but as soon as I finish with it, I will make a pull request

**Comment by kingster** [comment]
> Some of the features are closed-source, but some are not; I am negotiating to release them!

👍  Looking forward to your contributions :) 

PS: Closing this ticket for now.
