### ISSUE TITLE
Support for VXLAN Encapsulation

### ISSUE THREAD

**Issue by ddelapp** [voiceip/oreka#97]
I've been trying to configure Orkaudio to work via AWS Traffic Mirroring.  Their process mirrors traffic via VXLAN-encapsulated packets on port 4789.  Is there currently a way to handle traffic coming in via this message?  I can see traffic coming into the server but Orkaudio does not recognize it right now.

https://docs.aws.amazon.com/vpc/latest/mirroring/traffic-mirroring-packet-formats.html

**Comment by kingster** [comment]
Okay, wasn't aware of this. Can you maybe share a pcap file of a mirrored call, so that I can analyse what changes are required to support that?

**Comment by kingster** [comment]
Hi @ddelapp

Can you please give the changes from #101 a try? Binary builds are available from the [Checks Tab](https://github.com/voiceip/oreka/actions/runs/1791128909) 

I couldn't get any sample pcap file for a voip calls, so these changes are based on the rfc. If possible please do share a pcap file if you find any issues.

**Comment by kingster** [comment]
@ddelapp were you able to try out the changes and see if orkaudio is correctly able to record the calls?
